#  $ docker-compose up -d
#  $ docker-compose logs -f config
  
version: '3.3'

services:
    db:
        image: zainamin22/mysqlfleetx
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
            
    fleetx:
        image: zainamin22/fleetx
        depends_on:
            - db
        ports:
            - 8080:8080
