package com.zzeebee.databasemodel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reminders generated by hbm2java
 */
@Entity
@Table(name="reminders"
    ,catalog="iefleetx"
)
public class Reminders  implements java.io.Serializable {


     private Integer reminderId;
     private String reminderType;
     private String reminderTitle;
     private String reminderDescription;
     private String issuedTo;
     private Long issuedTime;
     private String issuedType;
     private Integer issuedToId;

    public Reminders() {
    }

    public Reminders(String reminderType, String reminderTitle, String reminderDescription, String issuedTo, Long issuedTime, String issuedType, Integer issuedToId) {
       this.reminderType = reminderType;
       this.reminderTitle = reminderTitle;
       this.reminderDescription = reminderDescription;
       this.issuedTo = issuedTo;
       this.issuedTime = issuedTime;
       this.issuedType = issuedType;
       this.issuedToId = issuedToId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="reminder_id", unique=true, nullable=false)
    public Integer getReminderId() {
        return this.reminderId;
    }
    
    public void setReminderId(Integer reminderId) {
        this.reminderId = reminderId;
    }

    
    @Column(name="reminder_type", length=500)
    public String getReminderType() {
        return this.reminderType;
    }
    
    public void setReminderType(String reminderType) {
        this.reminderType = reminderType;
    }

    
    @Column(name="reminder_title", length=500)
    public String getReminderTitle() {
        return this.reminderTitle;
    }
    
    public void setReminderTitle(String reminderTitle) {
        this.reminderTitle = reminderTitle;
    }

    
    @Column(name="reminder_description", length=500)
    public String getReminderDescription() {
        return this.reminderDescription;
    }
    
    public void setReminderDescription(String reminderDescription) {
        this.reminderDescription = reminderDescription;
    }

    
    @Column(name="issued_to", length=500)
    public String getIssuedTo() {
        return this.issuedTo;
    }
    
    public void setIssuedTo(String issuedTo) {
        this.issuedTo = issuedTo;
    }

    
    @Column(name="issued_time")
    public Long getIssuedTime() {
        return this.issuedTime;
    }
    
    public void setIssuedTime(Long issuedTime) {
        this.issuedTime = issuedTime;
    }

    
    @Column(name="issued_type", length=500)
    public String getIssuedType() {
        return this.issuedType;
    }
    
    public void setIssuedType(String issuedType) {
        this.issuedType = issuedType;
    }

    
    @Column(name="issued_to_id")
    public Integer getIssuedToId() {
        return this.issuedToId;
    }
    
    public void setIssuedToId(Integer issuedToId) {
        this.issuedToId = issuedToId;
    }




}


