package com.zzeebee.databasemodel;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceEntry generated by hbm2java
 */
@Entity
@Table(name="service_entry"
    ,catalog="iefleetx"
)
public class ServiceEntry  implements java.io.Serializable {


     private Integer serviceEntryId;
     private Admin admin;
     private Vehicle vehicle;
     private Vendor vendor;
     private Integer odometerReading;
     private String wstatus;
     private Long startTime;
     private Long endTime;
     private Long lastPerformed;
     private String wlabels;
     private String description;
     private String wtitle;
     private String serviceTaskName;
     private String serviceTaskDescription;
     private String serviceTaskStatus;

    public ServiceEntry() {
    }

    public ServiceEntry(Admin admin, Vehicle vehicle, Vendor vendor, Integer odometerReading, String wstatus, Long startTime, Long endTime, Long lastPerformed, String wlabels, String description, String wtitle, String serviceTaskName, String serviceTaskDescription, String serviceTaskStatus) {
       this.admin = admin;
       this.vehicle = vehicle;
       this.vendor = vendor;
       this.odometerReading = odometerReading;
       this.wstatus = wstatus;
       this.startTime = startTime;
       this.endTime = endTime;
       this.lastPerformed = lastPerformed;
       this.wlabels = wlabels;
       this.description = description;
       this.wtitle = wtitle;
       this.serviceTaskName = serviceTaskName;
       this.serviceTaskDescription = serviceTaskDescription;
       this.serviceTaskStatus = serviceTaskStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="service_entry_id", unique=true, nullable=false)
    public Integer getServiceEntryId() {
        return this.serviceEntryId;
    }
    
    public void setServiceEntryId(Integer serviceEntryId) {
        this.serviceEntryId = serviceEntryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id")
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vender_id")
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    
    @Column(name="odometer_reading")
    public Integer getOdometerReading() {
        return this.odometerReading;
    }
    
    public void setOdometerReading(Integer odometerReading) {
        this.odometerReading = odometerReading;
    }

    
    @Column(name="wstatus", length=250)
    public String getWstatus() {
        return this.wstatus;
    }
    
    public void setWstatus(String wstatus) {
        this.wstatus = wstatus;
    }

    
    @Column(name="start_time")
    public Long getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="end_time")
    public Long getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="last_performed")
    public Long getLastPerformed() {
        return this.lastPerformed;
    }
    
    public void setLastPerformed(Long lastPerformed) {
        this.lastPerformed = lastPerformed;
    }

    
    @Column(name="wlabels", length=1000)
    public String getWlabels() {
        return this.wlabels;
    }
    
    public void setWlabels(String wlabels) {
        this.wlabels = wlabels;
    }

    
    @Column(name="description", length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="wtitle", length=500)
    public String getWtitle() {
        return this.wtitle;
    }
    
    public void setWtitle(String wtitle) {
        this.wtitle = wtitle;
    }

    
    @Column(name="service_task_name", length=500)
    public String getServiceTaskName() {
        return this.serviceTaskName;
    }
    
    public void setServiceTaskName(String serviceTaskName) {
        this.serviceTaskName = serviceTaskName;
    }

    
    @Column(name="service_task_description", length=1000)
    public String getServiceTaskDescription() {
        return this.serviceTaskDescription;
    }
    
    public void setServiceTaskDescription(String serviceTaskDescription) {
        this.serviceTaskDescription = serviceTaskDescription;
    }

    
    @Column(name="service_task_status", length=500)
    public String getServiceTaskStatus() {
        return this.serviceTaskStatus;
    }
    
    public void setServiceTaskStatus(String serviceTaskStatus) {
        this.serviceTaskStatus = serviceTaskStatus;
    }




}


